Этап 3: верстка и JSX
Andrey-Kargin/movies-explorer-frontend pull request #1
Opened 2023-07-11 01:05 UTC by Andrey-Kargin

Прошу прощения за позднюю отправку на проверку
Сделал все по ТЗ и макету, оставил лишь поля валидации для 4 этапа диплома

2023-07-11 06:37 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
У Вас получилась хорошая работа для первого раза. Будет еще 3 итерации для того, чтобы над ней можно было еще поработать и она выгодно смотрелась в Вашем портфолио.
Вносите правки без спешки, следите за тем, что изменилось после внесения той или иной правки в элементе. Убедитесь перед отправкой, что все правки внесены. Если есть трудности - обращайтесь к наставнику и старшему студенту, они обязательно Вам помогут.

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

* https://yadi.sk/d/jsnZ2dQxSLrsOA https://yadi.sk/d/WI76jQ00-9Dy1A https://yadi.sk/d/xVVKlE_r6_ut9w https://yadi.sk/d/J6ttJOUsTcXzXg всем страницам на уровне родительского блока следует установить высоту равную высоте вьюпорта. Также обратите внимание, что на страницах 404, профиль, регистрация и вход в макете выравнивание по вертикали идет относительно высоты вьюпорта, это значит, что на любых других устройствах оно должно центрироваться без фиксации высоты по макету не образовывая вертикальный скролл. Для реализации можно использовать технологию построения через флекс/грид, когда контент центрируется, а шапка прижата к верху, а футер к низу. Также на главной сделать липкий футер прижав хедер и растянув основной контент [Как создать липкий футер с помощью flexbox](https://webformyself.com/kak-sozdat-lipkij-futer-s-pomoshhyu-flexbox/).

Страница Главная
* Все разрешения https://yadi.sk/d/UMRlIfYQ4ZItuA
* 768 https://yadi.sk/i/sTcwtVMYrTS57w
* 320 https://yadi.sk/i/ltR_3kD8-NiwHA https://yadi.sk/d/zimh93wzQymAPQ

Страницы Вход/Регистрация
* 1280 https://yadi.sk/d/R10bq-fYJovBmQ
* 768 https://yadi.sk/d/Oew8b4NTO70vyg

Хедер авторизованного
* 1280 https://yadi.sk/d/MlTdU12VIufIJA

Страницы фильмы/сохраненные
* 1280 https://yadi.sk/d/4BENwYpufL_jXQ https://yadi.sk/d/phTUo2ftwno8BA
* 768/320 https://yadi.sk/d/pvib2MG4R6umrw

Меню
* 768 https://yadi.sk/d/2vbjxNY9CVFKkA
* 320 https://yadi.sk/d/_6DRJs-atRVR9w

- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [ ] <!--5.55--> Именование классов сделаны по БЭМ.

* есть ошибки по БЭМ. https://yadi.sk/d/E3YLLJVrqLuAiw Модификатор расположен без сущности. Проверить правильность наименования классов можно также тут: https://nglazov.github.io/bem-validator-page/
* https://yadi.sk/d/jfSqPWZtwlzpmA в именовании основывайтесь на логический смысл элемента, т.к. контент внутри может измениться, будет труднее поддерживать, т.к. название будет непонятно, также старайтесь не использовать числовые имена.
* https://yadi.sk/i/8OK2c0ds6KmkEw Здесь также можно использовать именование по типу кнопок, т.к. регистрация может быть заменена на любое другое слово и станет непонятно, что за ссылки. Здесь хорошо подойдут вариации сложных модификаторов, напр., основная кнопка, кнопка с текстом и т.д.

- [ ] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.

* https://yadi.sk/i/KHTtkTWE7eTw9Q В проекте фиксирована высота и установлена прокрутка внутри блока, ее следует удалить, чтобы был скролл у браузера, это лучше для навигации
* https://yadi.sk/d/DMU3L_1CfS-F7A https://yadi.sk/d/kUbY_dBlLBGb-A В любом месте где есть контент не следует делать фиксацию по высоте, т.к. контент может измениться и это не должно поломать отображение. Если блок содержит фоновое изображение и контент используйте минимальную высоту, Вам следует самостоятельно на примере найти и исправить все похожие случаи

- [ ] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

* https://yadi.sk/d/QOiVjg3mYKyM7g https://yadi.sk/d/zSbd43XQBaGk_g https://yadi.sk/d/ALw9R3xc7iIr3g и т.д. главный контент страниц хорошо бы оформить main, а внутри него разместить семантические секции section
* https://yadi.sk/i/rlSkFXQTaUmKdg кнопку внутри ссылки можно удалить, здесь это лишняя вложенность, ссылку можно стилизовать как кнопку.
* navigation - рекомендуется тег навигации nav
* https://yadi.sk/i/r50RC9HrUyJcmw нет заголовка 1 уровня на отдельной странице

- [ ] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.

* movies-card__save-btn movies-card__delete-btn - расположите элементы в потоке

- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [ ] <!--3.38--> Работа модальных окон настроена.

* https://yadi.sk/d/5O0btK8KuaPE2Q на странице с профилем, при нажатии на редактирование используйте логику по макету https://yadi.sk/d/6t0HBnIsbrFF3A

- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [ ] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.

* https://yadi.sk/d/VBPKkiWY3PCuvg https://yadi.sk/d/dXJ84Cxy6iQj8w нет ховер эффекта

- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [ ] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.

* https://yadi.sk/d/UDgq6J6fvS8deg https://yadi.sk/d/-CqkL5rJ_6RcXw Всем полям следует стилизовать состояния focus и outline по макету или на свое усмотрение, чтобы при переключении через tab или установлении фокуса, было визуально выделено поле.

- [ ] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.

* Поля не проходят валидацию, только при правильно заполненных полях можно зайти в профиль, также следует отобразить состояния ошибки по макету, когда поле заполнено некорректно, можно использовать required

- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [ ] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.

* https://yadi.sk/d/IwCTnpOvO80cVA нет описания альт текста

- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 56

## Доп. Комментарии:
- https://yadi.sk/d/nP2waF3WINiXVg ховер эффект также можно добавить стрелочкам
* portfolio__link-icon navigation__profile-link-img promo__img Хорошей практикой считается отображать декоративные изображения на псевдоклассах `:before` и `:after` https://habr.com/ru/post/154319/

2023-07-12 00:43 UTC, Andrey-Kargin commented
Сделал все согласно ревью, единственное не получается никак сделать отображения кастомных ошибок в подготовленных <span> при валидации, а так вполне работоспоснобный код который не дает пройти на линк при ошибки валидации. Был бы рад услышать обратную связь с небольшой подсказкой на данную проблему, спасибо!

2023-07-12 07:24 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
Готово второе ревью Вашей работы.
Для реализации проверки правильности заполнения полей и отображении статуса ошибки рекомендую просмотреть тему про валидацию на платформе https://yadi.sk/i/N6klez1HzhPJhA, нужно будет повесить на поля обработчики.

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

* https://yadi.sk/i/rq-U-eEnAdZwEg можно центрировать относительно вьюпорта

Страница Главная
* 768 https://yadi.sk/i/IOGO_le5K2SSow размер шрифта, https://yadi.sk/i/P0iS-JcuWPcL8A высота эл.списка, https://yadi.sk/i/WbUCq9SkgXlL4Q размер шрифта
* 320 https://yadi.sk/i/NSLyCaB2-CrBLA отступ, https://yadi.sk/i/NSLyCaB2-CrBLA высота эл.списка

Страницы Вход/Регистрация
* 1280 https://yadi.sk/d/kVn1d4LQCRE9OA расстояние до кнопки

Хедер авторизованного
* 1280 https://yadi.sk/d/0gT7V3SoO4I0Rg

Меню
* 768 https://yadi.sk/d/4jLyPBV7AKIUEQ
* 320 https://yadi.sk/d/ZCaWx43YVBG6hQ

- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [ ] <!--5.55--> Именование классов сделаны по БЭМ.

* Сохраняются ошибки по БЭМ. https://yadi.sk/d/nzQY32Op8Fn79w https://yadi.sk/d/qZKic0p0Uj0z8w Проверить правильность наименования классов можно также тут: https://nglazov.github.io/bem-validator-page/

- [ ] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.

* https://yadi.sk/d/GP_Od5MnS2nRuw В любом месте где есть контент не следует делать фиксацию по высоте, т.к. контент может измениться и это не должно поломать отображение. Если блок содержит фоновое изображение и контент используйте минимальную высоту, Вам следует самостоятельно на примере найти и исправить все похожие случаи

- [x] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.
- [ ] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.

* movies-card__save-btn movies-card__delete-btn - расположите элементы в потоке

- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [x] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [x] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.
- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [x] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.
- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 71

## Доп. Комментарии:
- https://yadi.sk/d/bPdioij17SlIqw здесь статус ошибки изначально скрывается, добавьте состояния через модификатор, т.к. здесь будет ответ если вдруг при сохранении произойдет непредвиденная ошибка.
- https://yadi.sk/d/h-MUfB05yVlSHg после введения всех данных в поля следует переходить на страницу с фильмами, т.к. предполагается, что вход осуществлен. Сейчас перебрасывает на окно входа.

2023-07-12 13:58 UTC, Savallera approved these changes
# Резюме по работе:

Здравствуйте!
Поздравляю Ваш проект принят, желаю дальнейших успехов!

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [x] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.
- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [x] <!--5.55--> Именование классов сделаны по БЭМ.
- [x] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.
- [x] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.
- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [x] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.
- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [x] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.
- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 100

2023-07-12 14:38 UTC, merged